import 'package:flutter/cupertino.dart';

class LetterPage extends StatefulWidget {
  const LetterPage({super.key});

  @override
  State<LetterPage> createState() => _LetterPageState();
}

class _LetterPageState extends State<LetterPage> {
  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.all(8.0),
      child: SingleChildScrollView(
        child: Text(
          '    Hello, my name is Derek Ashcraft, I am an Oakton High School student and former Reston Herndon Little League player and have been involved in many other Reston Herndon Little League events since. I was drawn to this topic because I have played and coached a variety of youth sports at a variety of levels. This topic is important to me because I believe that youth sports, if done correctly, can be one of the most impactful things someone can do to prepare themselves for adult life. Additionally, youth sports is an excellent opportunity to teach participants a variety of life lessons while also providing them with exercise and entertainment.'
          '\n\n    Youth sports are one of the greatest learning opportunities for life available to children and young adults. However, adults have a tendency to forget this and instead “[overemphasize] winning” (Bonavolontà). In some instances, adults have even turned to physical violence as they did in Colorado during a seven year old little league game as a result of a poor ruling by a 13 year old umpire: “Parents are dropping F-bombs, and pointing fingers trying to get others thrown out. Finally, all hell breaks loose. Coaches argue. Parents get into it with one another. And it ends in a fight that goes viral across the globe.” ("When You Attend a Youth Sports Event, Know Your Role!"). As a result of this example of exceptionally poor behavior, “[f]ive people [were] arrested” and “two [of them were] suspended from their jobs” ("When You Attend a Youth Sports Event, Know Your Role!"). Additionally, “their season [was] canceled”, meaning these children would no longer get to play and reap the benefits of playing ("When You Attend a Youth Sports Event, Know Your Role!"). Furthermore, it is incredibly unlikely that these kids will want to continue playing baseball, or any other sport because of these parents’ poor behavior. In another instance “in St. Louis, a youth football coach of 9- and 10-year-olds was shot four times by a parent upset with his son\'s playing time”, which is far worse than the fight at the Little League game (Borelli). Not only is this obviously intolerable behavior, especially in the context of youth sports, but it has also ruined that family’s and child’s life far beyond the missed opportunity of youth sports. These two examples show extreme cases of poor parent behavior; however, more minor misconduct is present in most every youth sporting event, especially competitions. Poor parent behavior, as seen in these examples, is a large contributor to the fact that in 2020, only “54.1% of children aged 6-17 years participated in sports in the past 12 months” (Black). Furthermore, only “70.2% [of] children with a family income of 400% or more of [the Federal Poverty Level]” participated in youth sports in the past 12 months, in 2020. Despite the fact that most people in this income bracket would not have trouble paying for youth sports, which can be expensive, roughly 30% of those children choose not to play youth sports, likely because of a poor experience as a result of poor parent behavior. To conclude, even minor misconduct can mitigate the reward that is available to children who participate in youth sports, which makes having a system in place to discourage or prevent poor behavior from adults in youth sporting events essential.'
          '\n\n    One possible solution is to implement “a zero tolerance policy for official abuse and poor spectator and coach behavior at youth sporting events” ("When You Attend a Youth Sports Event, Know Your Role!"). This solution would give officials the power to eject coaches and spectators during competitions and coaches the same power over spectators during practices or other events. If someone was to be ejected, they would no longer be welcome at any team events for the rest of the season. In order to account for poor judgement and edge cases, someone who gets ejected would have the opportunity to appeal to a commissioner or another designated person. This solution could also take other forms such as the duration of the ban being for a certain number of events or even being permanent.'
          '\n\n    At youth sporting events there are “four [roles]: Coach: leads and organizes the athletes, Athlete: participates in the competition, Fan: cheers on the participants, Official/referee: applies the rules to the best of his/her ability” ("When You Attend a Youth Sports Event, Know Your Role!"). Often parents violate proper behavior when they attempt to hold more than one role at a time, such as trying to be a fan and a coach or a coach and an official. A zero tolerance policy would be an effective solution because it would prevent adults from taking on more than one role at a time. For instance, if a fan or coach was attempting to be both their respective role and an official, the officials have the power to eject that person, and if a fan was trying to be a coach, the coach would have the power to eject that fan. Other role combinations could also result in behavior that warrants an ejection, however, those combinations are relatively uncommon.'
          '\n\n    Another possible solution is to completely eliminate parents from the experience. This would completely eliminate poor adult behavior during events as they would not even be present and potentially improve player performance and ability, a big reason parents are so aggressive to begin with. This solution is fairly self-explanatory and simply consists of removing spectators during official events, and encouraging general detachment from the experience by adults the rest of the time. This solution is very cutthroat, however, it reduces the risk of conflict at an event to almost zero, while helping the kids learn to get better at their sport and be more independent in general. Additionally, this solution mimics “[m]any elite athletes[‘] hands off approach to their kid’s youth sports experience”, a strategy proven to work by their success (Magness).'
          '\n\n    This solution would almost completely eliminate the chance for poor adult behavior at youth sporting events because there would only be a handful of adults present, the coaches and the officials, who are not even always adults. However, a solution such as this one would likely come with heavy pushback from parents, that would have to be effectively managed. Parents often desire the chance for their child to play at the next level, which can come with financial benefits, a potential motive for parents. Therefore, parents conclude that they need to push their children to be as good at their sport as possible in order to give them the best chance to play at the next level. However, reduced competitiveness in youth sports often leads to better performance during events and better development in the long term leading to higher chances of being able to play at the collegiate or even professional level, where the money parents desire exists. This can be learned from the fact that elite athletes are “relatively more laid back about their young kids’ athletic endeavors… They know that it’s a long, windy path, and that in order to get through, the deep motivation and relentless drive is going to have to come from within” (Magness). This concept can also be seen through “Norway, [which has] a population that is roughly the size of Minnesota, [and] they don’t even keep score until age 13. In the last winter Olympics, Norway won 39 medals. Twice as many as the US and more than any country ever in a single winter Olympics.” (Bradley). Therefore, games and other youth sporting events should be low pressure situations for players, which is most easily achieved through no parental involvement. Additionally, when parents learn of the benefits of having a disconnect with their children’s sports, they might even want to disassociate themselves, reducing the overall pushback from parents.'
          '\n\n    One counter argument might state that parents\' time and emotional involvement in their children’s youth sports is what makes parents willing to invest so much time and money into youth sports; saying their “fervor and fandom fuels early Saturday morning scrimmages, long drives to tournaments and endless bake sales” (Sherwood). Parents’ investment in youth sports has driven it to be “an industry that is, in fact, bigger than the NFL or the NBA”, without this investment there would be fewer leagues, less events, and less resources available, therefore reducing the number of children who get to participate in youth sports and reducing the impact for those who do. Thus, maintaining parent engagement is essential to the success of the youth sports as a whole and to the reward children receive by participating.'
          '\n\n    However, this argument is flawed because it suggests that not allowing parents to misbehave at youth sporting events would affect their willingness to invest time and money for their children to participate. This argument is built on parents’ “love for [their] kids and, for many, [their] love for the game”, not their ability to go to the events and exhibit poor behavior, as the motivation for parents to invest in their child’s youth sports experience (Sherwood). Sometimes, this passion turns into poor behavior, not the other way around, meaning parents’ can still have great passion for their children and their teams while still exhibiting proper sportsmanship.'
          '\n\n    To conclude, youth sports is one of the greatest opportunities for children to learn life skills, become athletic, and of course have fun. However, parents tend to ruin or damage the experience for their children and other players through poor behavior at events. This misbehavior leads to players quitting, and therefore missing out on the benefits of the experience, or disliking the experience, leading to diminished results. Therefore, it is important that leagues, such as Reston Herndon Little League, implement zero tolerance rules to combat poor parent behavior.'
        ),
      ),
    );
  }
}
